#############################################################################
# Makefile for building: 2048.app/Contents/MacOS/2048
# Generated by qmake (3.0) (Qt 5.3.1)
# Project:  2048.pro
# Template: app
# Command: /Users/tobyyi/Qt5.3.1/5.3/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile 2048.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG -DQT_QUICK_LIB -DQT_QML_LIB -DQT_WIDGETS_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I../../Qt5.3.1/5.3/clang_64/mkspecs/macx-clang -I. -I../../Qt5.3.1/5.3/clang_64/lib/QtQuick.framework/Versions/5/Headers -I../../Qt5.3.1/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers -I../../Qt5.3.1/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I../../Qt5.3.1/5.3/clang_64/lib/QtNetwork.framework/Versions/5/Headers -I../../Qt5.3.1/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers -I../../Qt5.3.1/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/AGL.framework/Headers -F/Users/tobyyi/Qt5.3.1/5.3/clang_64/lib
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6
LIBS          = $(SUBLIBS) -F/Users/tobyyi/Qt5.3.1/5.3/clang_64/lib -framework QtQuick -framework QtQml -framework QtNetwork -framework QtCore -framework QtGui -framework QtWidgets -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /Users/tobyyi/Qt5.3.1/5.3/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp qrc_qml.cpp
OBJECTS       = main.o \
		qrc_qml.o
DIST          = ../../Qt5.3.1/5.3/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/qdevice.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/device_config.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/common/shell-unix.conf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/common/unix.conf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/common/mac.conf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/common/macx.conf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/common/clang.conf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/qconfig.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/qt_config.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/spec_post.prf \
		../../.qmake.stash \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/default_pre.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/mac/default_pre.prf \
		deployment.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/default_post.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/qml_debug.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/declarative_debug.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/warn_on.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/qt.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/resources.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/moc.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/uic.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/exceptions.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/yacc.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/lex.prf \
		2048.pro src/main.cpp
QMAKE_TARGET  = 2048
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = 2048.app/Contents/MacOS/2048

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk \
		-mmacosx-version-min=10.6 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile 2048.app/Contents/PkgInfo 2048.app/Contents/Resources/empty.lproj 2048.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@test -d 2048.app/Contents/MacOS/ || mkdir -p 2048.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: 2048.pro ../../Qt5.3.1/5.3/clang_64/mkspecs/macx-clang/qmake.conf ../../Qt5.3.1/5.3/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/qdevice.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/device_config.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/common/shell-unix.conf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/common/unix.conf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/common/mac.conf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/common/macx.conf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/common/clang.conf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/qconfig.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/qt_config.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/spec_post.prf \
		../../.qmake.stash \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/default_pre.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/mac/default_pre.prf \
		deployment.pri \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/default_post.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/qml_debug.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/declarative_debug.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/warn_on.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/qt.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/resources.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/moc.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/uic.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/exceptions.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/yacc.prf \
		../../Qt5.3.1/5.3/clang_64/mkspecs/features/lex.prf \
		2048.pro \
		src/qml.qrc \
		/Users/tobyyi/Qt5.3.1/5.3/clang_64/lib/QtQuick.framework/QtQuick.prl \
		/Users/tobyyi/Qt5.3.1/5.3/clang_64/lib/QtQml.framework/QtQml.prl \
		/Users/tobyyi/Qt5.3.1/5.3/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		/Users/tobyyi/Qt5.3.1/5.3/clang_64/lib/QtCore.framework/QtCore.prl \
		/Users/tobyyi/Qt5.3.1/5.3/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/tobyyi/Qt5.3.1/5.3/clang_64/lib/QtWidgets.framework/QtWidgets.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile 2048.pro
../../Qt5.3.1/5.3/clang_64/mkspecs/features/spec_pre.prf:
../../Qt5.3.1/5.3/clang_64/mkspecs/qdevice.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/features/device_config.prf:
../../Qt5.3.1/5.3/clang_64/mkspecs/common/shell-unix.conf:
../../Qt5.3.1/5.3/clang_64/mkspecs/common/unix.conf:
../../Qt5.3.1/5.3/clang_64/mkspecs/common/mac.conf:
../../Qt5.3.1/5.3/clang_64/mkspecs/common/macx.conf:
../../Qt5.3.1/5.3/clang_64/mkspecs/common/gcc-base.conf:
../../Qt5.3.1/5.3/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Qt5.3.1/5.3/clang_64/mkspecs/common/clang.conf:
../../Qt5.3.1/5.3/clang_64/mkspecs/common/clang-mac.conf:
../../Qt5.3.1/5.3/clang_64/mkspecs/qconfig.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/features/qt_functions.prf:
../../Qt5.3.1/5.3/clang_64/mkspecs/features/qt_config.prf:
../../Qt5.3.1/5.3/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt5.3.1/5.3/clang_64/mkspecs/features/spec_post.prf:
../../.qmake.stash:
../../Qt5.3.1/5.3/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt5.3.1/5.3/clang_64/mkspecs/features/default_pre.prf:
../../Qt5.3.1/5.3/clang_64/mkspecs/features/mac/default_pre.prf:
deployment.pri:
../../Qt5.3.1/5.3/clang_64/mkspecs/features/resolve_config.prf:
../../Qt5.3.1/5.3/clang_64/mkspecs/features/default_post.prf:
../../Qt5.3.1/5.3/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt5.3.1/5.3/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt5.3.1/5.3/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt5.3.1/5.3/clang_64/mkspecs/features/qml_debug.prf:
../../Qt5.3.1/5.3/clang_64/mkspecs/features/declarative_debug.prf:
../../Qt5.3.1/5.3/clang_64/mkspecs/features/warn_on.prf:
../../Qt5.3.1/5.3/clang_64/mkspecs/features/qt.prf:
../../Qt5.3.1/5.3/clang_64/mkspecs/features/resources.prf:
../../Qt5.3.1/5.3/clang_64/mkspecs/features/moc.prf:
../../Qt5.3.1/5.3/clang_64/mkspecs/features/unix/opengl.prf:
../../Qt5.3.1/5.3/clang_64/mkspecs/features/uic.prf:
../../Qt5.3.1/5.3/clang_64/mkspecs/features/unix/thread.prf:
../../Qt5.3.1/5.3/clang_64/mkspecs/features/mac/rez.prf:
../../Qt5.3.1/5.3/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt5.3.1/5.3/clang_64/mkspecs/features/exceptions.prf:
../../Qt5.3.1/5.3/clang_64/mkspecs/features/yacc.prf:
../../Qt5.3.1/5.3/clang_64/mkspecs/features/lex.prf:
2048.pro:
src/qml.qrc:
/Users/tobyyi/Qt5.3.1/5.3/clang_64/lib/QtQuick.framework/QtQuick.prl:
/Users/tobyyi/Qt5.3.1/5.3/clang_64/lib/QtQml.framework/QtQml.prl:
/Users/tobyyi/Qt5.3.1/5.3/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
/Users/tobyyi/Qt5.3.1/5.3/clang_64/lib/QtCore.framework/QtCore.prl:
/Users/tobyyi/Qt5.3.1/5.3/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/tobyyi/Qt5.3.1/5.3/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile 2048.pro

qmake_all: FORCE

2048.app/Contents/PkgInfo: 
	@test -d 2048.app/Contents || mkdir -p 2048.app/Contents
	@$(DEL_FILE) 2048.app/Contents/PkgInfo
	@echo "APPL????" >2048.app/Contents/PkgInfo
2048.app/Contents/Resources/empty.lproj: 
	@test -d 2048.app/Contents/Resources || mkdir -p 2048.app/Contents/Resources
	@touch 2048.app/Contents/Resources/empty.lproj
	
2048.app/Contents/Info.plist: 
	@test -d 2048.app/Contents || mkdir -p 2048.app/Contents
	@$(DEL_FILE) 2048.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@BUNDLEIDENTIFIER@,com.dtuandui.myfirst.2048,g" -e "s,@EXECUTABLE@,2048,g" -e "s,@TYPEINFO@,????,g" ../../Qt5.3.1/5.3/clang_64/mkspecs/macx-clang/Info.plist.app >2048.app/Contents/Info.plist
dist: 
	@test -d .tmp/20481.0.0 || mkdir -p .tmp/20481.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/20481.0.0/ && $(COPY_FILE) --parents src/qml.qrc .tmp/20481.0.0/ && $(COPY_FILE) --parents src/main.cpp .tmp/20481.0.0/ && (cd `dirname .tmp/20481.0.0` && $(TAR) 20481.0.0.tar 20481.0.0 && $(COMPRESS) 20481.0.0.tar) && $(MOVE) `dirname .tmp/20481.0.0`/20481.0.0.tar.gz . && $(DEL_FILE) -r .tmp/20481.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r 2048.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: src/qml.qrc \
		src/DayOfView.qml \
		src/GameTips.qml \
		src/qml/Cell.qml \
		src/qml/logic.js \
		src/qml/CustomBtn.qml \
		src/qml/GameOverWnd.qml \
		src/qml/Board.qml \
		src/qml/ScoreBoard.qml \
		src/qml/OptionsWnd.qml \
		src/qml/main.qml
	/Users/tobyyi/Qt5.3.1/5.3/clang_64/bin/rcc -name qml src/qml.qrc -o qrc_qml.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean 

####### Compile

main.o: src/main.cpp ../../Qt5.3.1/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		../../Qt5.3.1/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		../../Qt5.3.1/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/QQmlApplicationEngine \
		../../Qt5.3.1/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmlapplicationengine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/2048/bin || mkdir -p $(INSTALL_ROOT)/opt/2048/bin
	$(DEL_FILE) -r "$(INSTALL_ROOT)/opt/2048/bin/2048.app"
	
	-$(INSTALL_DIR) "2048.app" "$(INSTALL_ROOT)/opt/2048/bin/2048.app"

uninstall_target: FORCE
	-$(DEL_FILE) -r "$(INSTALL_ROOT)/opt/2048/bin/2048.app"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/2048/bin/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

